# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryptedIM.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='encryptedIM.proto',
  package='cosc435',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x65ncryptedIM.proto\x12\x07\x63osc435\"3\n\x0e\x62\x61sicIMmessage\x12\x10\n\x08nickname\x18\x01 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\t\"A\n\x12\x65ncryptedIMmessage\x12\n\n\x02iv\x18\x01 \x02(\x0c\x12\x0b\n\x03mac\x18\x02 \x02(\x0c\x12\x12\n\ncipherText\x18\x03 \x02(\x0c')
)




_BASICIMMESSAGE = _descriptor.Descriptor(
  name='basicIMmessage',
  full_name='cosc435.basicIMmessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nickname', full_name='cosc435.basicIMmessage.nickname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='cosc435.basicIMmessage.content', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)


_ENCRYPTEDIMMESSAGE = _descriptor.Descriptor(
  name='encryptedIMmessage',
  full_name='cosc435.encryptedIMmessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iv', full_name='cosc435.encryptedIMmessage.iv', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mac', full_name='cosc435.encryptedIMmessage.mac', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cipherText', full_name='cosc435.encryptedIMmessage.cipherText', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['basicIMmessage'] = _BASICIMMESSAGE
DESCRIPTOR.message_types_by_name['encryptedIMmessage'] = _ENCRYPTEDIMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

basicIMmessage = _reflection.GeneratedProtocolMessageType('basicIMmessage', (_message.Message,), dict(
  DESCRIPTOR = _BASICIMMESSAGE,
  __module__ = 'encryptedIM_pb2'
  # @@protoc_insertion_point(class_scope:cosc435.basicIMmessage)
  ))
_sym_db.RegisterMessage(basicIMmessage)

encryptedIMmessage = _reflection.GeneratedProtocolMessageType('encryptedIMmessage', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTEDIMMESSAGE,
  __module__ = 'encryptedIM_pb2'
  # @@protoc_insertion_point(class_scope:cosc435.encryptedIMmessage)
  ))
_sym_db.RegisterMessage(encryptedIMmessage)


# @@protoc_insertion_point(module_scope)